# Default values for portal.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

#ingress:
  # -- Additional annotations to add to the ingress
  #annotations: {}
service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  annotations: {
    kubernetes.io/ingress.class: "nginx"
  }
  path: /
  hosts:
    - host: portal-prod.cloud.lan

  # -- Configures TLS for the ingress if needed. If multiple ingresses share
  # the same hostname, only one of them needs a TLS configuration.
  tls: []


image:
  repository: nexus.local/portal
  tag: $CI_COMMIT_TAG
pull_secret: ""

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
